name: Docker Image CI

on:
  schedule: 
   - cron: '0 0 * */3 0'
  workflow_dispatch:

jobs:
  ltsc2022:
    strategy:
      matrix:
        WIN_VER: ["2022", "2019"]
    runs-on: windows-${{ matrix.WIN_VER }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Login to GHCR
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build
      run: >
        docker build
        --build-arg WIN_VER=ltsc${{ matrix.WIN_VER }}
        -t ${{ secrets.DOCKERHUB_USERNAME }}/chocolatey:ltsc${{ matrix.WIN_VER }}
        -t ghcr.io/${{ github.repository_owner }}/chocolatey:ltsc${{ matrix.WIN_VER }}
        if ( ${{ strategy.job-index }} -eq 0 ) { " -t ${{ secrets.DOCKERHUB_USERNAME }}/chocolatey" }
        if ( ${{ strategy.job-index }} -eq 0 ) { " -t ghcr.io/${{ github.repository_owner }}/chocolatey" }
        .
    - name: push
      run: |
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/chocolatey --all-tags
        docker push ghcr.io/${{ github.repository_owner }}/chocolatey --all-tags
