name: Docker Image CI

on:
  schedule: 
   - cron: '0 0 * */3 0'
  workflow_dispatch:

jobs:
  build:
    env:
      WIN_VER_LATEST: ltsc2022
    strategy:
      fail-fast: false
      matrix:
        include:
        - WIN_VER: ltsc2025
          BASE_IMAGE: dotnet/nightly/runtime
          DOTNET_VERSION: "9.0"
        - WIN_VER: ltsc2022
          BASE_IMAGE: dotnet/runtime
          DOTNET_VERSION: "9.0"
        - WIN_VER: ltsc2019
          BASE_IMAGE: dotnet/framework/runtime
          DOTNET_VERSION: "4.8"
        - WIN_VER: ltsc2016
          BASE_IMAGE: dotnet/framework/runtime
          DOTNET_VERSION: "4.8"
        - WIN_VER: 20H2
          BASE_IMAGE: dotnet/framework/runtime
          DOTNET_VERSION: "4.8"
        - WIN_VER: 2009
          BASE_IMAGE: dotnet/framework/runtime
          DOTNET_VERSION: "4.8"
        - WIN_VER: 2004
          BASE_IMAGE: dotnet/framework/runtime
          DOTNET_VERSION: "4.8"
#        - WIN_VER: 1909
#          BASE_IMAGE: dotnet/framework/runtime
#          DOTNET_VERSION: "4.8"
#        - WIN_VER: 1903
#          BASE_IMAGE: dotnet/framework/runtime
#          DOTNET_VERSION: "4.8"
        - WIN_VER: 1803
          BASE_IMAGE: dotnet/framework/runtime
          DOTNET_VERSION: "4.8"

    runs-on: windows-2025
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Login to GHCR
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build
      run: >
        docker build
        --build-arg BASE_IMAGE=${{ matrix.BASE_IMAGE }}
        --build-arg DOTNET_VERSION=${{ matrix.DOTNET_VERSION }}
        --build-arg WIN_VER=${{ matrix.WIN_VER }}
        --tag=${{ secrets.DOCKERHUB_USERNAME }}/chocolatey:${{ matrix.WIN_VER }}
        --tag=ghcr.io/${{ github.repository_owner }}/chocolatey:${{ matrix.WIN_VER }}
        --isolation=hyperv
        .
    - name: Tag latest
      if: ${{ matrix.WIN_VER == env.WIN_VER_LATEST }}
      run: |
        docker tag ${{ secrets.DOCKERHUB_USERNAME }}/chocolatey:${{ matrix.WIN_VER }} ${{ secrets.DOCKERHUB_USERNAME }}/chocolatey
        docker tag ghcr.io/${{ github.repository_owner }}/chocolatey:${{ matrix.WIN_VER }} ghcr.io/${{ github.repository_owner }}/chocolatey
    - name: push
      run: |
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/chocolatey --all-tags
        docker push ghcr.io/${{ github.repository_owner }}/chocolatey --all-tags

  trigger-next-workflow:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Trigger next workflow (visualstudio-build-tools-docker)
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: docker-image.yml
          repo: ${{ github.repository_owner }}/visualstudio-build-tools-docker
          token: ${{ secrets.VISUALSTUDIO_BUILD_TOOLS_DOCKER }}
