name: Test

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: windows-2025
    steps:
    - name: Write new Docker configuration
      run: |
        echo '{"hosts": ["npipe://"], "data-root": "D:\\docker"}' > C:\ProgramData\docker\config\daemon.json
        net stop docker
        net start docker
