name: Test

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: windows-2025
    steps:
    - name: Test
      run: |
        Get-WmiObject -Class Win32_LogicalDisk | Select-Object DeviceID, VolumeName, Size, FreeSpace | ForEach-Object {
          [PSCustomObject]@{
              Unidad       = $_.DeviceID
              Volumen      = $_.VolumeName
              'Espacio Total (GB)' = [math]::round($_.Size / 1GB, 2)
              'Espacio Libre (GB)' = [math]::round($_.FreeSpace / 1GB, 2)
          }
        }
