name: Test

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: windows-2025
    steps:
    - name: Write new Docker configuration
      run: |
        echo '{"hosts": ["npipe://"], "data-root": "D:\\docker"}' > C:\ProgramData\docker\config\daemon.json
    - name: Stop Docker service
      run: net stop docker
    - name: Stop Docker service
      run: net start docker
    - name: List new configuration
      run: docker info | Select-String "Docker Root Dir"
        
